[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"

[dev]
  command = "npm run start"
  publish = "dist"
  
# Proxy Lambda functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect to custom 404
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404